name: Compile LaTeX to PDF

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup LaTeX
        uses: dante-ev/latex-action@v2
        with:
          additional_packages: 'geometry'

      - name: Compile LaTeX to PDF
        run: pdflatex card.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: card-pdf
          path: card.pdf
